import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, Calendar, Camera, CheckCircle2, Copy, Database, FileImage, Fingerprint, HardDrive, Maximize2, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button, StatusBadge } from "../components/ui";
import { api } from "../lib/api";
import { formatBytes, formatDate, percent } from "../lib/utils";
import type { ImageDetail } from "../types";

function EvidenceBar({ label, value }: { label: string; value: number | null }) {
  if (value === null) return null;
  return <div><div className="mb-1 flex justify-between font-mono text-[9px] uppercase tracking-wide text-muted"><span>{label}</span><span>{percent(value)}</span></div><div className="h-1 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-acid" style={{ width: `${Math.max(3, value * 100)}%` }} /></div></div>;
}

export function ImageDetailPage() {
  const { id } = useParams(); const navigate = useNavigate();
  const [image, setImage] = useState<ImageDetail | null>(null); const [error, setError] = useState(""); const [confirming, setConfirming] = useState(false); const [deleting, setDeleting] = useState(false);
  useEffect(() => { if (id) api<ImageDetail>(`/images/${id}`).then(setImage).catch((reason: Error) => setError(reason.message)); }, [id]);
  useEffect(() => {
    if (!id || !image || !["PENDING", "PROCESSING"].includes(image.status)) return;
    const timer = window.setTimeout(() => api<ImageDetail>(`/images/${id}`).then(setImage).catch(() => undefined), 4000);
    return () => window.clearTimeout(timer);
  }, [id, image]);
  async function remove() { if (!id) return; setDeleting(true); try { await api(`/images/${id}?confirm=true`, { method: "DELETE" }); navigate("/gallery"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Deletion failed"); setConfirming(false); } finally { setDeleting(false); } }
  if (error) return <div className="panel rounded-2xl p-8"><h1 className="text-xl font-semibold">Image unavailable</h1><p className="mt-2 text-sm text-muted">{error}</p><Link to="/gallery"><Button className="mt-5" variant="secondary">Back to gallery</Button></Link></div>;
  if (!image) return <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="skeleton aspect-[4/3] rounded-[28px]" /><div className="skeleton h-[34rem] rounded-[28px]" /></div>;
  const metadata = [[FileImage,"Format",image.mime_type.split("/")[1].toUpperCase()],[HardDrive,"File size",formatBytes(image.file_size)],[Maximize2,"Dimensions",image.width && image.height ? `${image.width} × ${image.height}` : "Processing"],[Calendar,"Uploaded",formatDate(image.created_at)],[Camera,"Camera",image.camera_model ?? "Not available"],[Database,"Object key",image.object_key.split("/").at(-1) ?? image.object_key]] as const;
  return <>
    <div className="mb-6 flex items-center justify-between"><Link to="/gallery" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm text-muted hover:text-ink"><ArrowLeft className="h-4 w-4" />Back to gallery</Link><Button variant="ghost" className="text-coral" onClick={() => setConfirming(true)}><Trash2 className="h-4 w-4" />Delete</Button></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="panel overflow-hidden rounded-[28px]"><div className="relative grid min-h-[22rem] place-items-center bg-[#14181e] sm:min-h-[34rem]">{image.original_url ? <img src={image.original_url} alt={image.original_filename} className="max-h-[72vh] w-full object-contain" /> : <FileImage className="h-10 w-10 text-muted" />}<div className="absolute left-4 top-4"><StatusBadge status={image.status} /></div></div></section><aside className="panel rounded-[28px] p-5 sm:p-6"><p className="eyebrow">Image record</p><h1 className="mt-3 break-words text-2xl font-semibold tracking-[-.035em]">{image.original_filename}</h1><p className="mt-2 text-xs text-muted">Stored privately · signed preview</p><div className="mt-7 divide-y divide-line border-y border-line">{metadata.map(([Icon,label,value]) => <div key={label} className="flex items-start gap-3 py-3.5"><Icon className="mt-0.5 h-4 w-4 text-muted" /><div className="min-w-0"><p className="text-[11px] text-muted">{label}</p><p className="mt-1 truncate text-sm" title={value}>{value}</p></div></div>)}</div><div className="mt-6"><div className="flex items-center gap-2"><Fingerprint className="h-4 w-4 text-acid" /><p className="text-sm font-semibold">SHA-256</p></div><p className="mt-2 break-all rounded-xl bg-black/25 p-3 font-mono text-[10px] leading-5 text-muted">{image.sha256}</p></div>{image.exact_duplicate_of && <Link to={`/images/${image.exact_duplicate_of.id}`} className="mt-5 block rounded-xl border border-coral/20 bg-coral/[.07] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-coral"><Copy className="h-4 w-4" />Exact duplicate detected</div><p className="mt-2 truncate text-xs text-muted">Matches {image.exact_duplicate_of.original_filename} · SHA-256 100%</p></Link>}</aside></div>
    <section className="mt-5 panel rounded-[28px] p-5 sm:p-6">
      <div className="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="eyebrow">Multi-signal intelligence</p><h2 className="mt-2 text-xl font-semibold">Why these images belong together</h2><p className="mt-2 max-w-2xl text-sm text-muted">ImageVault combines multi-view OpenCLIP, three perceptual fingerprints, color composition, and frame geometry. No single weak signal can create a near-duplicate match.</p></div>{image.batch_id && <Link to={`/duplicates?batch=${image.batch_id}`}><Button variant="secondary">Open batch report</Button></Link>}</div>
      {image.similar_images.length === 0 ? <div className="rounded-2xl border border-dashed border-line py-12 text-center"><CheckCircle2 className="mx-auto h-6 w-6 text-acid" /><p className="mt-3 text-sm font-medium">No strong visual matches</p><p className="mt-1 text-xs text-muted">The available evidence did not pass the configured confidence gates.</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{image.similar_images.map((similar) => <article key={similar.image.id} className="overflow-hidden rounded-2xl border border-line bg-black/10"><Link to={`/images/${similar.image.id}`} className="focus-ring group block"><div className="relative aspect-[16/9] overflow-hidden bg-[#171b21]">{similar.image.thumbnail_url && <img src={similar.image.thumbnail_url} alt={similar.image.original_filename} className="h-full w-full object-cover transition group-hover:scale-[1.03]" />}<div className="absolute inset-x-0 bottom-0 h-16 bg-gradient-to-t from-black/80 to-transparent" /><span className="absolute bottom-3 right-3 rounded-full bg-white px-2.5 py-1 font-mono text-[10px] font-semibold text-black">{percent(similar.similarity_score)}</span></div></Link><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{similar.image.original_filename}</p><p className="mt-1 text-xs text-muted">{similar.classification} · {similar.match_type}</p></div></div><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3"><EvidenceBar label="AI" value={similar.clip_score} /><EvidenceBar label="Structure" value={similar.perceptual_score} /><EvidenceBar label="Color" value={similar.color_score} /><EvidenceBar label="Frame" value={similar.aspect_score} /></div><div className="mt-4 flex flex-wrap gap-1.5">{similar.reasons.map((reason) => <span key={reason} className="rounded-full border border-line px-2 py-1 text-[10px] text-muted">{reason}</span>)}</div></div></article>)}</div>}
    </section>
    <AnimatePresence>{confirming && <div className="fixed inset-0 z-50 grid place-items-center p-4"><motion.button aria-label="Close confirmation" className="absolute inset-0 bg-black/75" initial={{ opacity: 0 }} animate={{ opacity: 1 }} onClick={() => setConfirming(false)} /><motion.div role="dialog" aria-modal="true" className="panel relative z-10 w-full max-w-md rounded-[28px] p-6" initial={{ scale: .96, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><button onClick={() => setConfirming(false)} aria-label="Close" className="absolute right-4 top-4 p-2 text-muted"><X className="h-4 w-4" /></button><h2 className="text-xl font-semibold">Delete this image?</h2><p className="mt-2 text-sm leading-6 text-muted">The original object, thumbnail, database record, and vector will be permanently removed.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setConfirming(false)}>Cancel</Button><Button variant="danger" loading={deleting} onClick={remove}>Delete permanently</Button></div></motion.div></div>}</AnimatePresence>
  </>;
}
