import { BrainCircuit, CircleDollarSign, Cloud, KeyRound, LockKeyhole, SlidersHorizontal } from "lucide-react";
import { PageHeading } from "../components/ui";
import { useAuth } from "../providers/AuthProvider";

export function SettingsPage() {
  const { user } = useAuth();
  return <>
    <PageHeading eyebrow="Vault configuration" title="Transparent by design." description="Runtime settings are environment-controlled so the same containers can move from Compose to Minikube without changing application code." />
    <div className="grid gap-5 xl:grid-cols-[1fr_.7fr]"><section className="panel rounded-[28px] p-5 sm:p-6"><p className="eyebrow">Account</p><div className="mt-6 flex items-center gap-4 border-b border-line pb-6"><div className="grid h-12 w-12 place-items-center rounded-full bg-lilac/15 font-semibold text-lilac">{user?.display_name.split(" ").map((part) => part[0]).join("").slice(0,2).toUpperCase()}</div><div><p className="font-semibold">{user?.display_name}</p><p className="text-sm text-muted">{user?.email}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{[[BrainCircuit,"Visual model","OpenCLIP ViT-B/32"],[SlidersHorizontal,"Match threshold","0.85 similarity"],[KeyRound,"Authentication","Expiring JWT"],[LockKeyhole,"Object access","Private + signed URLs"]].map(([Icon,label,value]) => { const ItemIcon = Icon as typeof BrainCircuit; return <div key={label as string} className="rounded-xl border border-line bg-white/[.02] p-4"><ItemIcon className="h-4 w-4 text-acid" /><p className="mt-5 text-xs text-muted">{label as string}</p><p className="mt-1 text-sm font-semibold">{value as string}</p></div>; })}</div><div className="mt-6 rounded-xl border border-line bg-black/15 p-4"><p className="text-sm font-semibold">Change runtime configuration</p><p className="mt-2 text-xs leading-5 text-muted">Update the values in your local <code className="font-mono text-lilac">.env</code> file and restart the affected containers. Secrets are never edited or displayed in this interface.</p></div></section><aside className="space-y-5"><div className="panel rounded-[28px] p-5 sm:p-6"><p className="eyebrow">Privacy boundary</p><Cloud className="mt-7 h-6 w-6 text-acid" /><h2 className="mt-5 text-lg font-semibold">Your laptop is the cloud.</h2><p className="mt-2 text-sm leading-6 text-muted">Images, hashes, thumbnails, and embeddings remain inside your Docker or Minikube environment. No external AI inference is configured.</p></div><div className="rounded-[28px] border border-acid/20 bg-acid/[.06] p-5 sm:p-6"><CircleDollarSign className="h-6 w-6 text-acid" /><p className="mt-5 text-3xl font-semibold tracking-[-.04em]">₹0</p><p className="mt-1 text-sm font-semibold">Additional software & cloud cost</p><p className="mt-2 text-xs leading-5 text-muted">Open-source services on existing student hardware. Hardware, electricity, and internet are not represented as free.</p></div></aside></div>
  </>;
}
