import { Activity, Box, CheckCircle2, CircleDot, Cpu, Database, ExternalLink, Gauge, HardDrive, Network, RefreshCw, Server, Sparkles, TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Button, PageHeading } from "../components/ui";
import { api } from "../lib/api";
import type { ComponentStatus, SystemStatus } from "../types";

function ServiceCard({ name, detail, status, icon: Icon }: { name: string; detail: string | null; status: string; icon: typeof Server }) {
  const healthy = ["healthy", "idle"].includes(status);
  return <div className="panel rounded-2xl p-5"><div className="flex items-start justify-between"><div className={`grid h-10 w-10 place-items-center rounded-xl ${healthy ? "bg-acid/10 text-acid" : "bg-coral/10 text-coral"}`}><Icon className="h-4 w-4" /></div><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider ${healthy ? "border-acid/20 bg-acid/10 text-acid" : "border-coral/20 bg-coral/10 text-coral"}`}><span className={`h-1.5 w-1.5 rounded-full ${healthy ? "bg-acid" : "bg-coral"}`} />{status}</span></div><h3 className="mt-7 font-semibold">{name}</h3><p className="mt-1 text-xs text-muted">{detail ?? "No detail reported"}</p></div>;
}

export function SystemPage() {
  const [data, setData] = useState<SystemStatus | null>(null); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { setRefreshing(true); try { setData(await api<SystemStatus>("/system/status")); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Status unavailable"); } finally { setRefreshing(false); } }, []);
  useEffect(() => { load(); const timer = window.setInterval(load, 15000); return () => window.clearInterval(timer); }, [load]);
  const services: [string, ComponentStatus, typeof Server][] = data ? [["API",data.api,Network],["PostgreSQL + pgvector",data.database,Database],["MinIO object storage",data.object_storage,HardDrive],["AI worker",data.worker,Cpu],["OpenCLIP model",data.embedding_model,Sparkles]] : [];
  return <>
    <PageHeading eyebrow="Operational intelligence" title="The whole private cloud, visible." description="Live component checks, queue state, and observability entry points for your DevOps demonstration." action={<Button variant="secondary" loading={refreshing} onClick={load}><RefreshCw className="h-4 w-4" />Refresh</Button>} />
    {error && <div className="mb-5 flex gap-3 rounded-2xl border border-coral/20 bg-coral/10 p-4 text-sm text-orange-100"><TriangleAlert className="h-4 w-4" />{error}</div>}
    {!data ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <div className="skeleton h-44 rounded-2xl" key={index} />)}</div> : <><div className="mb-5 flex flex-col justify-between gap-3 rounded-2xl border border-acid/20 bg-acid/[.055] p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-acid/10"><CheckCircle2 className="h-5 w-5 text-acid" /></div><div><p className="font-semibold">ImageVault is {data.status}</p><p className="text-xs text-muted">Application version v{data.version} · auto-refresh every 15 seconds</p></div></div><div className="flex gap-6"><div><p className="eyebrow">Pending jobs</p><p className="mt-1 text-xl font-semibold">{data.pending_jobs}</p></div><div><p className="eyebrow">Redis queue</p><p className="mt-1 text-xl font-semibold">{data.queue_size ?? "—"}</p></div></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{services.map(([name,service,Icon]) => <ServiceCard key={name} name={name} detail={service.detail} status={service.status} icon={Icon} />)}</div></>}
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="panel rounded-[28px] p-5 sm:p-6"><p className="eyebrow">Request path</p><h2 className="mt-2 text-xl font-semibold">Service-oriented architecture</h2><div className="mt-8 flex flex-col items-stretch gap-3 lg:flex-row lg:items-center">{[[Gauge,"React","Web client"],[Network,"Nginx","Gateway"],[Server,"FastAPI","REST API"],[CircleDot,"Redis","Job queue"],[Cpu,"Worker","Local AI"]].map(([Icon,label,detail], index) => { const ItemIcon = Icon as typeof Server; return <div key={label as string} className="contents"><div className="flex flex-1 items-center gap-3 rounded-xl border border-line bg-white/[.02] p-3 lg:block lg:text-center"><ItemIcon className="h-4 w-4 text-lilac lg:mx-auto" /><div><p className="text-xs font-semibold lg:mt-3">{label as string}</p><p className="mt-0.5 font-mono text-[9px] uppercase tracking-wide text-muted">{detail as string}</p></div></div>{index < 4 && <div className="hidden h-px w-3 bg-line lg:block" />}</div>; })}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-line bg-white/[.02] p-4"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-acid" /><p className="text-sm font-semibold">PostgreSQL + pgvector</p></div><p className="mt-2 text-xs leading-5 text-muted">Users, metadata, jobs, SHA-256 hashes, and normalized vectors.</p></div><div className="rounded-xl border border-line bg-white/[.02] p-4"><div className="flex items-center gap-2"><Box className="h-4 w-4 text-acid" /><p className="text-sm font-semibold">MinIO</p></div><p className="mt-2 text-xs leading-5 text-muted">Private S3-compatible originals and efficient WebP thumbnails.</p></div></div></section><aside className="panel rounded-[28px] p-5 sm:p-6"><p className="eyebrow">Observability</p><h2 className="mt-2 text-xl font-semibold">Inspect the platform</h2><p className="mt-3 text-sm leading-6 text-muted">Prometheus collects application and worker metrics. Grafana ships with a ready-to-use ImageVault dashboard.</p><div className="mt-7 space-y-3"><a href="http://localhost:3001" target="_blank" rel="noreferrer" className="focus-ring flex items-center justify-between rounded-xl border border-line bg-white/[.025] p-4 text-sm font-semibold hover:border-muted"><span className="flex items-center gap-2"><Activity className="h-4 w-4 text-acid" />Open Grafana</span><ExternalLink className="h-4 w-4 text-muted" /></a><a href="http://localhost:9090" target="_blank" rel="noreferrer" className="focus-ring flex items-center justify-between rounded-xl border border-line bg-white/[.025] p-4 text-sm font-semibold hover:border-muted"><span className="flex items-center gap-2"><Gauge className="h-4 w-4 text-lilac" />Open Prometheus</span><ExternalLink className="h-4 w-4 text-muted" /></a></div></aside></div>
  </>;
}
